### ISSUE TITLE
Build Error on openshift

### ISSUE THREAD

**Issue by lixingcong** [TwidereProject/Twidere-API-Proxy-Go#4]
Hello, I am new here. I was confused when I create this apps on openshift. After clicking "CREATE APPLICATION", It shows errors bellow:

> The initial build for the application failed: Shell command '/sbin/runuser -s /bin/sh 56ba0cfa7628e1ae2f00007b -c "exec /usr/bin/runcon 'unconfined_u:system_r:openshift_t:s0:c3,c172' /bin/sh -c \"gear postreceive --init >> /tmp/initial-build.log 2>&1\""' returned an error. rc=255 .Last 10 kB of build output: Warning: Application 'golang' server exists without a pid file. Use force-stop to kill. Repairing links for 1 deployments Building git ref 'master', commit ab50428 ! A .godir is required. For instructions: ! http://mmcgrana.github.com/2012/09/getting-started-with-go-on-heroku ! https://www.openshift.com/kb/kb-TDOD-some-golang-instructions An error occurred executing 'gear postreceive' (exit code: 1) Error message: CLIENT_ERROR: Failed to execute: 'control build' for /var/lib/openshift/56ba0cfa7628e1ae2f00007b/go For more details about the problem, try running the command again with the '--trace' option.

Could you please help me? Thank you.

[Attachment:snapshot.png](http://pro_drive.byethost16.com/pic/?v=capture.png)

**Comment by lixingcong** [comment]
Solved!
Using an default golang cart, no pasting your git repo when creating app.
Then using git clone your repo to openshift repo.
:+1:

**Comment by DrayChou** [comment]
我直接创建的时候贴入地址会报错，然后试了创建之后 git 提交进去，然后 building 很久之后 started 了，然后访问站点还是报 503 的错误。
不清楚原因了。
